[window]
# Set the opacity of the terminal background (0.0 - fully transparent, 1.0 - fully opaque)
opacity = 0.9

# Padding around the terminal content
padding.x = 7
padding.y = 7

# Window decorations ("None", "Full")
decorations = "Full"

# Set the theme variant for decorations (use "Dark" or "Light")
decorations_theme_variant = "Light"

[font]
# Font configuration
# Use JetBrains Mono Nerd Font for all styles
normal.family = "JetBrains Mono Nerd Font"
bold.family = "JetBrains Mono Nerd Font"
italic.family = "JetBrains Mono Nerd Font"
bold_italic.family = "JetBrains Mono Nerd Font"

# Font size in points
size = 12.5

[colors]
# Set custom colors for the terminal
[colors.primary]
background = "#2E2B28" # Dark brown for background
foreground = "#E8E6E3" # Light cream for text

[colors.cursor]
text = "#2E2B28"       # Cursor text (same as background)
cursor = "#D0A88F"     # Cursor color (soft brown)

[colors.normal]
black = "#1E1C1A"      # Dark brown (almost black)
red = "#A44200"        # Rust red
green = "#7C6A4F"      # Brownish green (subtle)
yellow = "#B87F4B"     # Golden brown
blue = "#566573"       # Muted gray-blue
magenta = "#8E6F74"    # Soft plum
cyan = "#9E9375"       # Dusty teal
white = "#E8E6E3"      # Cream white

[colors.bright]
black = "#4A423F"      # Mid-tone brown
red = "#FF5700"        # Bright orange
green = "#A4907C"      # Warm brown
yellow = "#FFD080"     # Pale gold
blue = "#7898A1"       # Muted steel blue
magenta = "#B88A8E"    # Soft pinkish plum
cyan = "#C4B88A"       # Golden beige
white = "#F9F6F3"      # Light cream
